---
title: Fly Kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  data:
    title: data
    output: true
email: flykitchenph@gmail.com
description: Grow your food business with xero-inbestment and high return!
baseurl: ''
url: "/"
twitter_username: flykitchenph
site_logo: "/assets/images/logo_1.png"
permalink: "/:title"
theme: minima
hero_image: "/assets/images/breadcrumb_bg.jpg"
sass:
  sass_dir: _sass
  style: compressed
site_preloader: true
